---
title: "Introduction: Credibility, Models, and Parameters"
output: html_document
---


# Introduction: Credibility, Models, and Parameters

## Bayesian Inference is Reallocation of Credibility Across Possibilities

## Possibilities Are Parameter Values in Descriptive Models

## The Steps of Bayesian Data Analysis

In general, Bayesian analysis of data follows these steps:

1. Identify the **data** relevant to the research questions.

What are the measurement scales of the data? 
Which data variables are to be predicted, and which data variables are
supposed to act as predictors?

2. Define a **descriptive model for the** relevant **data**. The mathematical form and its
parameters should be meaningful and appropriate to the theoretical purposes of the
analysis.

3. Specify a **prior distribution** on the parameters. The prior must pass muster with the
audience of the analysis, such as skeptical scientists.

4. Use Bayesian inference to **re-allocate credibility across parameter values**. Interpret
the posterior distribution with respect to theoretically meaningful issues (assuming
that the model is a reasonable description of the data; see next step).

5. Check that the posterior predictions mimic the data with reasonable 
accuracy (i.e., conduct a "**posterior predictive check**"). 
If not, then consider a different descriptive model.