---
title: "(Re)Doing Bayesain Data Analysis"
author: "R Pruim"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
output_dir: "../docs/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggformula)
library(rjags)
library(runjags)
library(rstan)
```



# What's in These Notes

This "book" is a companion to Kruschke's *Doing Bayesian Data Analysis*.
The main reasons for this companion are to use a different style of R code that includes:

* use of modern packages like `tidyverse`, `R2jags`, `bayesplot`, and `ggformula`;
* adherence to a different style guide;
* less reliance on manually editing scripts and more use of resusable code available in packages;
* a workflow that takes advantage of RStudio and RMarkdown.

This is a work in progress. Please accept my apologies in advance for

* errors,
* inconsistencies
* lack of complete coverage

But feel free to post issues on github if you spot things that require attention
or care to make suggestions for improvement.

I’ll be teaching from this book in Spring 2019, so I expect rapid development
during those months.